import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Famous Pagodas In Myanmar",
  description: "Generated by create next app",
};

const lineShapes = [
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="verticalLines">

          <div className="line-1">
            <div className="myshapes">
              {lineShapes.map((shape, index) => (
                <div key={index} className={shape}></div>
              ))}
            </div>
          </div>

          <div className="line-2">
            <div className="myshapes">
              {lineShapes.map((shape, index) => (
                <div key={index} className={shape}></div>
              ))}
            </div>
          </div>

          <div className="line-3">
            <div className="myshapes">
              {lineShapes.map((shape, index) => (
                <div key={index} className={shape}></div>
              ))}
            </div>
          </div>

          <div className="line-4">
            <div className="myshapes">
              {lineShapes.map((shape, index) => (
                <div key={index} className={shape}></div>
              ))}
            </div>
          </div>
        </div>
        {children}
        </body>
    </html>
  );
}
